const K="sirohiFarmV3";
const empty={goats:[],health:[],breeding:[],sales:[],expenses:[],profile:{name:"Sirohi Goat Farm & Breeding Setup",owner:"",phone:"",location:""}};
let d=JSON.parse(localStorage.getItem(K)||JSON.stringify(empty));
const $=id=>document.getElementById(id), today=()=>new Date().toISOString().slice(0,10);
function save(){localStorage.setItem(K,JSON.stringify(d));render()}
function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function page(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");render()}
function modal(html){$("form").innerHTML=html;$("modal").classList.remove("hidden")}function closeModal(){$("modal").classList.add("hidden")}
function fld(label,html){return `<label class="formlabel">${label}</label>${html}`}
function openGoat(){modal(`<h2>Add Goat</h2>${fld("Tag / ID",'<input id="gtag" placeholder="SG-001">')}${fld("Name",'<input id="gname">')}${fld("Type",'<select id="gtype"><option>Doe</option><option>Buck</option><option>Kid</option></select>')}${fld("Breed",'<input id="gbreed" value="Sirohi">')}${fld("Sex",'<select id="gsex"><option>Female</option><option>Male</option></select>')}${fld("Date of Birth",'<input id="gdob" type="date">')}${fld("Weight (kg)",'<input id="gweight" type="number" step=".1">')}${fld("Purchase Price (₹)",'<input id="gpurchase" type="number">')}${fld("Notes",'<textarea id="gnote" rows="3"></textarea>')}<div class="actions"><button onclick="addGoat()">Save</button><button class="ghost" onclick="closeModal()">Cancel</button></div>`)}
function addGoat(){if(!gtag.value.trim())return alert("Enter Tag / ID");d.goats.push({id:Date.now(),tag:gtag.value.trim(),name:gname.value,type:gtype.value,breed:gbreed.value,sex:gsex.value,dob:gdob.value,weight:gweight.value,purchase:+gpurchase.value||0,note:gnote.value});closeModal();save()}
function openHealth(){modal(`<h2>Add Health Record</h2>${fld("Goat Tag",'<input id="htag">')}${fld("Date",`<input id="hdate" type="date" value="${today()}">`)}${fld("Type",'<select id="htype"><option>Vaccination</option><option>Deworming</option><option>Medicine</option><option>Illness</option><option>Check-up</option></select>')}${fld("Next Due Date",'<input id="hdue" type="date">')}${fld("Vaccine / Medicine / Details",'<textarea id="hdetail" rows="3"></textarea>')}<div class="actions"><button onclick="addHealth()">Save</button><button class="ghost" onclick="closeModal()">Cancel</button></div>`)}
function addHealth(){d.health.push({id:Date.now(),tag:htag.value,date:hdate.value,type:htype.value,due:hdue.value,detail:hdetail.value});closeModal();save()}
function openBreed(){modal(`<h2>Add Breeding Record</h2>${fld("Doe Tag",'<input id="bdoe">')}${fld("Buck Tag",'<input id="bbuck">')}${fld("Mating Date",'<input id="bdate" type="date">')}${fld("Expected Kidding",'<input id="bexp" type="date">')}${fld("Status",'<select id="bstatus"><option>Planned</option><option>Mated</option><option>Pregnant</option><option>Kidded</option><option>Failed</option></select>')}${fld("Kids Born",'<input id="bkids" type="number" min="0">')}${fld("Notes",'<textarea id="bnote" rows="3"></textarea>')}<div class="actions"><button onclick="addBreed()">Save</button><button class="ghost" onclick="closeModal()">Cancel</button></div>`)}
function addBreed(){d.breeding.push({id:Date.now(),doe:bdoe.value,buck:bbuck.value,date:bdate.value,expected:bexp.value,status:bstatus.value,kids:+bkids.value||0,note:bnote.value});closeModal();save()}
function openExpense(){modal(`<h2>Add Expense</h2>${fld("Date",`<input id="edate" type="date" value="${today()}">`)}${fld("Category",'<select id="ecat"><option>Feed</option><option>Medicine</option><option>Vaccination</option><option>Labour</option><option>Shed</option><option>Transport</option><option>Other</option></select>')}${fld("Amount (₹)",'<input id="eamount" type="number">')}${fld("Details",'<textarea id="edetail" rows="3"></textarea>')}<div class="actions"><button onclick="addExpense()">Save</button><button class="ghost" onclick="closeModal()">Cancel</button></div>`)}
function addExpense(){d.expenses.push({id:Date.now(),date:edate.value,category:ecat.value,amount:+eamount.value||0,detail:edetail.value});closeModal();save()}
function openSale(){modal(`<h2>Add Sale</h2>${fld("Goat Tag",'<input id="stag">')}${fld("Date",`<input id="sdate" type="date" value="${today()}">`)}${fld("Customer",'<input id="scustomer">')}${fld("Sale Amount (₹)",'<input id="samount" type="number">')}${fld("Payment Status",'<select id="spay"><option>Paid</option><option>Pending</option><option>Partial</option></select>')}${fld("Notes",'<textarea id="snote" rows="3"></textarea>')}<div class="actions"><button onclick="addSale()">Save</button><button class="ghost" onclick="closeModal()">Cancel</button></div>`)}
function addSale(){d.sales.push({id:Date.now(),tag:stag.value,date:sdate.value,customer:scustomer.value,amount:+samount.value||0,payment:spay.value,note:snote.value});closeModal();save()}
function del(type,id){if(confirm("Delete record?")){d[type]=d[type].filter(x=>x.id!==id);save()}}
function renderGoats(){let q=($("goatSearch")?.value||"").toLowerCase();let a=d.goats.filter(x=>(x.tag+" "+x.name+" "+x.breed).toLowerCase().includes(q));$("goatList").innerHTML=a.length?a.map(x=>`<div class="item"><strong>${esc(x.tag)}</strong><span class="pill">${esc(x.type)}</span><div class="meta">${esc(x.name||"")} • ${esc(x.breed)} • ${x.weight?esc(x.weight)+" kg":"No weight"}<br>DOB: ${esc(x.dob||"-")} • Purchase: ₹${x.purchase.toLocaleString("en-IN")}<br>${esc(x.note||"")}</div><button class="danger" onclick="del('goats',${x.id})">Delete</button></div>`).join(""):'<div class="empty">No goats found.</div>'}
function render(){
let preg=d.breeding.filter(x=>x.status==="Pregnant").length, sales=d.sales.reduce((s,x)=>s+x.amount,0), expenses=d.expenses.reduce((s,x)=>s+x.amount,0);
$("nGoats").textContent=d.goats.length;$("nDoes").textContent=d.goats.filter(x=>x.type==="Doe").length;$("nBucks").textContent=d.goats.filter(x=>x.type==="Buck").length;$("nPreg").textContent=preg;
$("overview").innerHTML=`<div class="statgrid"><div class="stat">Sales<b>₹${sales.toLocaleString("en-IN")}</b></div><div class="stat">Expenses<b>₹${expenses.toLocaleString("en-IN")}</b></div><div class="stat">Balance<b>₹${(sales-expenses).toLocaleString("en-IN")}</b></div><div class="stat">Kids born<b>${d.breeding.reduce((s,x)=>s+x.kids,0)}</b></div></div>`;
let due=d.health.filter(x=>x.due&&x.due>=today()).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,5);
$("alerts").innerHTML=due.length?due.map(x=>`<div class="notice">💉 <b>${esc(x.tag||"Farm")}</b> — ${esc(x.type)} due ${esc(x.due)}</div>`).join(""):'<div class="good">✓ No upcoming health dates recorded.</div>';
renderGoats();
$("healthList").innerHTML=d.health.length?d.health.slice().reverse().map(x=>`<div class="item"><strong>${esc(x.tag||"Farm")}</strong><span class="pill">${esc(x.type)}</span><div class="meta">${esc(x.date)}${x.due?" • Next due: "+esc(x.due):""}<br>${esc(x.detail)}</div><button class="danger" onclick="del('health',${x.id})">Delete</button></div>`).join(""):'<div class="empty">No health records.</div>';
$("breedList").innerHTML=d.breeding.length?d.breeding.slice().reverse().map(x=>`<div class="item"><strong>${esc(x.doe)}</strong> × ${esc(x.buck)} <span class="pill">${esc(x.status)}</span><div class="meta">Mating: ${esc(x.date||"-")} • Kidding: ${esc(x.expected||"-")}<br>Kids: ${x.kids} • ${esc(x.note||"")}</div><button class="danger" onclick="del('breeding',${x.id})">Delete</button></div>`).join(""):'<div class="empty">No breeding records.</div>';
$("expenseList").innerHTML=d.expenses.length?d.expenses.slice().reverse().map(x=>`<div class="item"><strong>${esc(x.category)}</strong><span class="pill">₹${x.amount.toLocaleString("en-IN")}</span><div class="meta">${esc(x.date)}<br>${esc(x.detail)}</div><button class="danger" onclick="del('expenses',${x.id})">Delete</button></div>`).join(""):'<div class="empty">No expenses.</div>';
$("saleList").innerHTML=d.sales.length?d.sales.slice().reverse().map(x=>`<div class="item"><strong>${esc(x.tag)}</strong><span class="pill">${esc(x.payment)}</span><div class="meta">${esc(x.date)} • ${esc(x.customer||"-")}<br>₹${x.amount.toLocaleString("en-IN")}<br>${esc(x.note||"")}</div><button class="danger" onclick="del('sales',${x.id})">Delete</button></div>`).join(""):'<div class="empty">No sales recorded.</div>';
$("finance").innerHTML=`<div class="statgrid"><div class="stat">Sales<b>₹${sales.toLocaleString("en-IN")}</b></div><div class="stat">Expenses<b>₹${expenses.toLocaleString("en-IN")}</b></div><div class="stat">Net<b>₹${(sales-expenses).toLocaleString("en-IN")}</b></div><div class="stat">Transactions<b>${d.sales.length+d.expenses.length}</b></div></div>`;
$("reportGoats").innerHTML=`Does: ${d.goats.filter(x=>x.type==="Doe").length} • Bucks: ${d.goats.filter(x=>x.type==="Buck").length} • Kids: ${d.goats.filter(x=>x.type==="Kid").length}<br>Pregnant: ${preg}`;
$("farmName").value=d.profile.name;$("owner").value=d.profile.owner;$("phone").value=d.profile.phone;$("location").value=d.profile.location;
}
function saveProfile(){d.profile={name:$("farmName").value,owner:$("owner").value,phone:$("phone").value,location:$("location").value};save();alert("Profile saved")}
function backup(){let blob=new Blob([JSON.stringify(d,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="sirohi-farm-v3-backup.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function restore(input){let f=input.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let x=JSON.parse(r.result);if(!x.goats||!x.health)throw 0;d={...empty,...x,profile:{...empty.profile,...(x.profile||{})}};save();alert("Backup restored")}catch(e){alert("Invalid backup file")}};r.readAsText(f)}
function resetAll(){if(confirm("Delete ALL farm data from this device?")){d=JSON.parse(JSON.stringify(empty));save()}}
let dp=null;addEventListener("beforeinstallprompt",e=>{e.preventDefault();dp=e;$("install").classList.remove("hidden")});$("install").onclick=async()=>{if(dp){dp.prompt();dp=null}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");render();