const K="sirohiFarmV2";let d=JSON.parse(localStorage.getItem(K)||'{"goats":[],"health":[],"breeding":[],"sales":[],"profile":{"name":"Sirohi Goat Farm & Breeding Setup","owner":"","phone":""}}');
const $=id=>document.getElementById(id);const today=()=>new Date().toISOString().slice(0,10);
function save(){localStorage.setItem(K,JSON.stringify(d));render()}function esc(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function page(id){document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));$(id).classList.add("active");render()}
function modal(html){$("form").innerHTML=html;$("modal").classList.remove("hidden")}function closeModal(){$("modal").classList.add("hidden")}
function fld(label,html){return `<label class="formlabel">${label}</label>${html}`}
function openGoat(){modal(`<h2>Add Goat</h2>${fld("Tag / ID",'<input id="gtag" placeholder="SG-001">')}${fld("Name",'<input id="gname">')}${fld("Type",'<select id="gtype"><option>Doe</option><option>Buck</option><option>Kid</option></select>')}${fld("Breed",'<input id="gbreed" value="Sirohi">')}${fld("Date of Birth",'<input id="gdob" type="date">')}${fld("Weight (kg)",'<input id="gweight" type="number" step=".1">')}${fld("Purchase Price (₹)",'<input id="gpurchase" type="number">')}${fld("Notes",'<textarea id="gnote" rows="3"></textarea>')}<div class="actions"><button onclick="addGoat()">Save</button><button class="ghost" onclick="closeModal()">Cancel</button></div>`)}
function addGoat(){if(!gtag.value.trim())return alert("Enter Tag / ID");d.goats.push({id:Date.now(),tag:gtag.value,name:gname.value,type:gtype.value,breed:gbreed.value,dob:gdob.value,weight:gweight.value,purchase:gpurchase.value,note:gnote.value});closeModal();save()}
function openHealth(){modal(`<h2>Add Health Record</h2>${fld("Goat Tag",'<input id="htag">')}${fld("Date",`<input id="hdate" type="date" value="${today()}">`)}${fld("Type",'<select id="htype"><option>Vaccination</option><option>Deworming</option><option>Medicine</option><option>Illness</option><option>Check-up</option></select>')}${fld("Vaccine / Medicine / Details",'<textarea id="hdetail" rows="3"></textarea>')}<div class="actions"><button onclick="addHealth()">Save</button><button class="ghost" onclick="closeModal()">Cancel</button></div>`)}
function addHealth(){d.health.push({id:Date.now(),tag:htag.value,date:hdate.value,type:htype.value,detail:hdetail.value});closeModal();save()}
function openBreed(){modal(`<h2>Add Breeding Record</h2>${fld("Doe Tag",'<input id="bdoe">')}${fld("Buck Tag",'<input id="bbuck">')}${fld("Mating Date",'<input id="bdate" type="date">')}${fld("Expected Kidding",'<input id="bexp" type="date">')}${fld("Status",'<select id="bstatus"><option>Planned</option><option>Mated</option><option>Pregnant</option><option>Kidded</option></select>')}${fld("Notes",'<textarea id="bnote" rows="3"></textarea>')}<div class="actions"><button onclick="addBreed()">Save</button><button class="ghost" onclick="closeModal()">Cancel</button></div>`)}
function addBreed(){d.breeding.push({id:Date.now(),doe:bdoe.value,buck:bbuck.value,date:bdate.value,expected:bexp.value,status:bstatus.value,note:bnote.value});closeModal();save()}
function openSale(){modal(`<h2>Add Sale</h2>${fld("Goat Tag",'<input id="stag">')}${fld("Date",`<input id="sdate" type="date" value="${today()}">`)}${fld("Customer",'<input id="scustomer">')}${fld("Sale Amount (₹)",'<input id="samount" type="number">')}${fld("Payment Status",'<select id="spay"><option>Paid</option><option>Pending</option><option>Partial</option></select>')}${fld("Notes",'<textarea id="snote" rows="3"></textarea>')}<div class="actions"><button onclick="addSale()">Save</button><button class="ghost" onclick="closeModal()">Cancel</button></div>`)}
function addSale(){d.sales.push({id:Date.now(),tag:stag.value,date:sdate.value,customer:scustomer.value,amount:samount.value,payment:spay.value,note:snote.value});closeModal();save()}
function del(type,id){if(confirm("Delete record?")){d[type]=d[type].filter(x=>x.id!==id);save()}}
function renderGoats(){let q=($("goatSearch")?.value||"").toLowerCase();let a=d.goats.filter(x=>(x.tag+x.name+x.breed).toLowerCase().includes(q));$("goatList").innerHTML=a.length?a.map(x=>`<div class="item"><strong>${esc(x.tag)}</strong><span class="pill">${esc(x.type)}</span><div class="meta">${esc(x.name||"")} • ${esc(x.breed)} • ${x.weight?esc(x.weight)+" kg":"No weight"}<br>DOB: ${esc(x.dob||"-")} • Purchase: ₹${esc(x.purchase||"0")}<br>${esc(x.note||"")}</div><button class="danger" onclick="del('goats',${x.id})">Delete</button></div>`).join(""):'<div class="empty">No goats found.</div>'}
function render(){let pregnant=d.breeding.filter(x=>x.status==="Pregnant").length;$("nGoats").textContent=d.goats.length;$("nDoes").textContent=d.goats.filter(x=>x.type==="Doe").length;$("nBucks").textContent=d.goats.filter(x=>x.type==="Buck").length;$("nPreg").textContent=pregnant;
$("snapshot").innerHTML=`<div>📅 Today: <b>${today()}</b></div><div>❤️ Pregnant does: <b>${pregnant}</b></div><div>💰 Sales recorded: <b>${d.sales.length}</b></div>`;renderGoats();
$("healthList").innerHTML=d.health.length?d.health.slice().reverse().map(x=>`<div class="item"><strong>${esc(x.tag||"Farm")}</strong><span class="pill">${esc(x.type)}</span><div class="meta">${esc(x.date)}<br>${esc(x.detail)}</div><button class="danger" onclick="del('health',${x.id})">Delete</button></div>`).join(""):'<div class="empty">No health records.</div>';
$("breedList").innerHTML=d.breeding.length?d.breeding.slice().reverse().map(x=>`<div class="item"><strong>${esc(x.doe)}</strong> × ${esc(x.buck)} <span class="pill">${esc(x.status)}</span><div class="meta">Mating: ${esc(x.date||"-")}<br>Expected kidding: ${esc(x.expected||"-")}<br>${esc(x.note||"")}</div><button class="danger" onclick="del('breeding',${x.id})">Delete</button></div>`).join(""):'<div class="empty">No breeding records.</div>';
$("saleList").innerHTML=d.sales.length?d.sales.slice().reverse().map(x=>`<div class="item"><strong>${esc(x.tag)}</strong><span class="pill">${esc(x.payment)}</span><div class="meta">${esc(x.date)} • ${esc(x.customer||"-")}<br>₹${esc(x.amount||"0")}<br>${esc(x.note||"")}</div><button class="danger" onclick="del('sales',${x.id})">Delete</button></div>`).join(""):'<div class="empty">No sales recorded.</div>';
$("farmName").value=d.profile.name;$("owner").value=d.profile.owner;$("phone").value=d.profile.phone}
function saveProfile(){d.profile={name:$("farmName").value,owner:$("owner").value,phone:$("phone").value};save();alert("Profile saved")}
function backup(){let blob=new Blob([JSON.stringify(d,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="sirohi-farm-backup.json";a.click()}
function restore(input){let f=input.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{d=JSON.parse(r.result);save();alert("Backup restored")}catch(e){alert("Invalid backup file")}};r.readAsText(f)}
function resetAll(){if(confirm("Delete all farm data?")){d={goats:[],health:[],breeding:[],sales:[],profile:{name:"Sirohi Goat Farm & Breeding Setup",owner:"",phone:""}};save()}}
let dp=null;addEventListener("beforeinstallprompt",e=>{e.preventDefault();dp=e;$("install").classList.remove("hidden")});$("install").onclick=async()=>{if(dp){dp.prompt();dp=null}};if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js");render();